repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
        exclude: ^radioplayer/(__init__|dataclasses).py$
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]
        exclude: ^radioplayer/(__init__|dataclasses).py$
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
        exclude: ^radioplayer/(__init__|dataclasses).py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^schemas/.*.xsd$
      - id: end-of-file-fixer
        exclude: ^schemas/.*.xsd$
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
