site_name: radioplayer-dataclasses
repo_url: https://github.com/radiorabe/python-radioplayer-dataclasses
repo_name: radiorabe/python-radioplayer-dataclasses

theme:
  name: "material"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - toc.integrate

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

extra:
  social:
    - icon: material/web
      link: https://rabe.ch

extra_css:
- css/style.css

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [radioplayer/dataclasses]
        options:
          show_if_no_docstring: true
          filters:
            - "!^_[^_]"
            - "!^radioplayer$"

nav:
  - README: index.md
  - API Reference: reference/radioplayer/dataclasses/dataclasses.md

watch:
  - README.md
  - radioplayer/dataclasses/
