name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages

jobs:

  xsdata-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements-dev.txt

      - name: Run xsdata
        run: xsdata -c .xsdata.xml schemas/

      - name: Check Diff
        run: git diff --exit-code

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements-dev.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', '3.9' ]
    name: Test python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -r requirements-dev.txt

      - run: python -mpytest --cov-fail-under=100
