name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@v0.7.1
  pytest:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@v0.7.1
  xsdata-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'

      - run: poetry install

      - name: Run xsdata
        run: poetry run xsdata -c .xsdata.xml schemas/

      - name: Check Diff
        run: git diff --exit-code
